# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeitem',
            name='spent_hour',
            field=models.FloatField(default=0.0),
        ),
    ]
