# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 05:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeManagement', '0002_auto_20171230_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSpentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=200)),
                ('remained_hour', models.FloatField()),
                ('completed_hour', models.FloatField(default=0.0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('time_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeManagement.TimeItem')),
            ],
        ),
    ]
