# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeManagement', '0003_timespentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='timespentitem',
            name='priority',
            field=models.IntegerField(default=7),
        ),
    ]
